mkdir -p build/llvm\/$BUILD_TRIPLE
pushd build/llvm\/$BUILD_TRIPLE
cmake -G Ninja \
   -DCMAKE_BUILD_TYPE=Release \
   -DCMAKE_INSTALL_PREFIX=$TOOLCHAIN_INSTALL\/$BUILD_TRIPLE \
   -DCMAKE_PREFIX_PATH=$TOOLCHAIN_INSTALL\/$BUILD_TRIPLE \
   -DLLVM_DEFAULT_TARGET_TRIPLE=$BUILD_TRIPLE \
   -DLLVM_ENABLE_CXX11=ON \
   -DLLVM_TARGET_ARCH=host \
   -DLLVM_TARGETS_TO_BUILD=$LLVM_TARGETS \
   ../../../sources/llvm;
popd
